#!/bin/bash

# script to auto increment the v0.1.xxxx patch number

# make all changes have been committed
#if [[ `git status --porcelain` ]]; then
#    echo "Must have a clean git status to continue"
#    exit 1
#fi

# create a new tag
RES=$(git show-ref --tags)
if [ -z "$RES" ]; then
    NEW_TAG=v1.0.0
else
    NEW_TAG=$(git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}')
fi

# add and push the tag
git tag $NEW_TAG -a -m "autogenerated tag"
git push origin $NEW_TAG
